// GENERATED by apps/desktop/scripts/generate-tokens.mjs — DO NOT EDIT.
// Source:    packages/design-system/tokens.json (the platform contract)
// Regenerate: node apps/desktop/scripts/generate-tokens.mjs
// Verify:    pnpm --filter @buddysaradhi/design-system verify
// Spec:      docs/design/overhaul-plan.md §6

import type { MaterialId } from "./tokens";

/**
 * The Tauri `WindowEffect` union, as published by
 * @tauri-apps/cli config.schema.json (WindowEffect enum). Kept as a local
 * type so this module never imports the Tauri runtime and stays usable
 * from the generator's own validation.
 */
export type TauriWindowEffect =
  | "titlebar"
  | "selection"
  | "menu"
  | "popover"
  | "sidebar"
  | "headerView"
  | "sheet"
  | "windowBackground"
  | "hudWindow"
  | "fullScreenUI"
  | "tooltip"
  | "contentBackground"
  | "underWindowBackground"
  | "underPageBackground"
  | "mica"
  | "micaDark"
  | "micaLight"
  | "tabbed"
  | "tabbedDark"
  | "tabbedLight"
  | "blur"
  | "acrylic"
  | "appearanceBased";

export type DesktopPlatform = "windows" | "macos" | "linux";

export interface NativeMaterialMapping {
  /** `null` = this platform cannot do a backdrop; use the `-solid` tokens. */
  readonly effects: readonly TauriWindowEffect[] | null;
  /** Whether the window must be transparent for the effect to be visible. */
  readonly requiresTransparentWindow: boolean;
  /** Why the mapping looks the way it does — surfaced in release notes. */
  readonly fidelity: "full" | "approximation" | "unsupported";
  readonly note: string;
}

export type NativeMaterialMap = Readonly<Record<MaterialId, Readonly<Record<DesktopPlatform, NativeMaterialMapping>>>>;

export const NATIVE_MATERIALS: NativeMaterialMap = {
  "minimal": {
    windows: { effects: null, requiresTransparentWindow: false, fidelity: "full", note: "No backdrop. The opaque canvas token is the window background." },
    macos: { effects: null, requiresTransparentWindow: false, fidelity: "full", note: "No vibrancy. The opaque canvas token is the window background." },
    linux: { effects: null, requiresTransparentWindow: false, fidelity: "full", note: "Tauri window effects are unsupported on Linux — and Minimal asks for none, so the result is exact rather than degraded." },
  },
  "acrylic": {
    windows: { effects: ["mica"], requiresTransparentWindow: true, fidelity: "approximation", note: "Mica (Windows 11). The native half of acrylic mode; the CSS material layer supplies the tint and blur in-webview." },
    macos: { effects: ["sidebar"], requiresTransparentWindow: true, fidelity: "full", note: "NSVisualEffectView sidebar vibrancy — the AppKit material whose documented use is a window sidebar, which is what this shell's rail is." },
    linux: { effects: null, requiresTransparentWindow: false, fidelity: "unsupported", note: "Tauri window effects are unsupported on Linux: acrylic falls back to the -solid tokens." },
  },
  "liquid-glass": {
    windows: { effects: ["mica"], requiresTransparentWindow: true, fidelity: "approximation", note: "Mica again — Tauri exposes neither MicaKind.BaseAlt nor MicaKind.Base, and AppKit has no Liquid Glass. Same native backdrop as acrylic; the CSS layer carries the difference." },
    macos: { effects: ["sidebar"], requiresTransparentWindow: true, fidelity: "approximation", note: "Same vibrancy material as acrylic — Tauri exposes no isEmphasized and AppKit has no Liquid Glass." },
    linux: { effects: null, requiresTransparentWindow: false, fidelity: "unsupported", note: "Tauri window effects are unsupported on Linux: liquid glass falls back to the -solid tokens." },
  },
};

/**
 * Resolve the window effect for a material on this platform. `null` is a
 * first-class answer: it means the caller must paint the `-solid` tokens.
 */
export function nativeMaterialFor(
  materialId: MaterialId,
  platform: DesktopPlatform,
): NativeMaterialMapping {
  return NATIVE_MATERIALS[materialId][platform];
}
