// Implements: docs/design/overhaul-plan.md §6 — Tauri/desktop token wiring.
//
// WHY A GENERATOR
// `packages/design-system/tokens.json` is the platform contract
// (overhaul-plan §2.2). 20 palettes x 3 material modes is ~1 900 colour values
// and a Tauri window config needs numeric RGB, not CSS. Hand-maintaining both is
// how two platforms end up disagreeing about what "canvas" is. This script is the
// only thing allowed to turn the contract into desktop files.
//
// The colour/CSS/TS mechanics below are intentionally duplicated from
// apps/mobile/scripts/generate-tokens.mjs rather than shared across app
// boundaries: a shared module would have to live in packages/, which no platform
// wave may touch, and an app importing another app's internals is worse. The
// duplication is bounded — the two generated `tokens.css` files must stay
// byte-identical apart from their `Regenerate:` banner line, and the two
// generated `src/theme/tokens.ts` must expose the same exported surface. Both
// are asserted by the diff step in docs/design/platform-tokens.md §7.
//
// INPUT RESOLUTION (documented per the W5 brief)
// apps/desktop does NOT declare `@buddysaradhi/design-system` (verified:
// apps/desktop/node_modules/@buddysaradhi holds only `shared` and `ui`), so the
// contract is read through a path relative to this file:
//   apps/desktop/scripts/../../.. -> repo root -> packages/design-system/tokens.json
// If the workspace package is ever linked, the require.resolve branch takes over.
//
// RUN
//   node apps/desktop/scripts/generate-tokens.mjs
//
// OUTPUTS (all generated, all DO NOT EDIT)
//   apps/desktop/src/styles/tokens.css     the web layer: custom properties with
//                                          the contract names + `-rgb` triplets
//   apps/desktop/src/theme/tokens.ts       typed palette/material/theme surface
//   apps/desktop/src/theme/native.ts       material -> Tauri window-effect map,
//                                          per platform, from this contract
//   apps/desktop/src-tauri/tauri.windows.conf.json
//   apps/desktop/src-tauri/tauri.macos.conf.json
//   apps/desktop/src-tauri/tauri.linux.conf.json
//
// FAIL-CLOSED
// Any shape/contract problem exits 1 and writes NOTHING.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const appRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = join(appRoot, "..", "..");

const BANNER_LINES = [
  "GENERATED by apps/desktop/scripts/generate-tokens.mjs — DO NOT EDIT.",
  "Source:    packages/design-system/tokens.json (the platform contract)",
  "Regenerate: node apps/desktop/scripts/generate-tokens.mjs",
  "Verify:    pnpm --filter @buddysaradhi/design-system verify",
  "Spec:      docs/design/overhaul-plan.md §6",
];

// ---------------------------------------------------------------------------
// 1. Read the contract
// ---------------------------------------------------------------------------

function resolveContractPath() {
  try {
    return require.resolve("@buddysaradhi/design-system/tokens.json");
  } catch {
    return join(repoRoot, "packages", "design-system", "tokens.json");
  }
}

const contractPath = resolveContractPath();
let contract;
try {
  contract = JSON.parse(readFileSync(contractPath, "utf8"));
} catch (cause) {
  process.stderr.write(`FATAL: cannot read the token contract at ${contractPath}\n`);
  process.stderr.write(`       ${cause instanceof Error ? cause.message : String(cause)}\n`);
  process.exit(1);
}

const problems = [];
const fail = (message) => problems.push(message);

const MATERIAL_IDS = ["minimal", "acrylic", "liquid-glass"];
const DEFAULT_PALETTE_ID = "inked";
const DEFAULT_MATERIAL_ID = "minimal";

if (!Array.isArray(contract.palettes) || contract.palettes.length === 0) {
  fail("tokens.json has no `palettes` array");
}
for (const id of MATERIAL_IDS) {
  if (!contract.materials || !contract.materials[id]) fail(`tokens.json is missing material "${id}"`);
}

const palettes = Array.isArray(contract.palettes) ? contract.palettes : [];
const STRUCTURE_KEYS = palettes.length > 0 ? Object.keys(palettes[0].structure ?? {}) : [];
const MATERIAL_KEYS =
  palettes.length > 0 ? Object.keys(palettes[0].materials?.[DEFAULT_MATERIAL_ID] ?? {}) : [];

const SOLID_PAIRS = [
  ["surface-overlay", "surfaceOverlaySolid"],
  ["surface-nav", "surfaceNavSolid"],
  ["surface-sheet", "surfaceSheetSolid"],
  ["surface-palette", "surfacePaletteSolid"],
];

const seenIds = new Set();
for (const palette of palettes) {
  for (const field of ["id", "name", "tier", "figma", "structure", "materials"]) {
    if (palette[field] === undefined) fail(`palette is missing "${field}"`);
  }
  if (seenIds.has(palette.id)) fail(`duplicate palette id "${palette.id}"`);
  seenIds.add(palette.id);
  if (Object.keys(palette.structure ?? {}).join(",") !== STRUCTURE_KEYS.join(",")) {
    fail(`palette "${palette.id}" has a different structure key set than "${palettes[0].id}"`);
  }
  for (const id of MATERIAL_IDS) {
    const layer = palette.materials?.[id];
    if (!layer) {
      fail(`palette "${palette.id}" is missing material "${id}"`);
      continue;
    }
    if (Object.keys(layer).join(",") !== MATERIAL_KEYS.join(",")) {
      fail(`palette "${palette.id}" material "${id}" has a different key set`);
    }
    for (const [translucent, solidKey] of SOLID_PAIRS) {
      if (!layer[translucent]) fail(`palette "${palette.id}" material "${id}" lacks "${translucent}"`);
      if (!palette.structure?.[solidKey]) {
        fail(`palette "${palette.id}" lacks the paired fallback "${solidKey}"`);
      }
    }
  }
}
if (palettes.length > 0 && !seenIds.has(DEFAULT_PALETTE_ID)) {
  fail(`default palette "${DEFAULT_PALETTE_ID}" is not in the contract`);
}

if (problems.length > 0) {
  process.stderr.write("FATAL: token contract does not satisfy what this generator needs:\n");
  for (const problem of problems) process.stderr.write(`  - ${problem}\n`);
  process.exit(1);
}

// ---------------------------------------------------------------------------
// 2. Colour maths — format conversion only
// ---------------------------------------------------------------------------

function parseColor(value, where) {
  const input = String(value).trim();
  const hex = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(input);
  if (hex) {
    const body = hex[1];
    const full =
      body.length === 3
        ? body
            .split("")
            .map((c) => c + c)
            .join("")
        : body;
    return {
      r: Number.parseInt(full.slice(0, 2), 16),
      g: Number.parseInt(full.slice(2, 4), 16),
      b: Number.parseInt(full.slice(4, 6), 16),
      a: 1,
    };
  }
  const fn = /^rgba?\(([^)]+)\)$/i.exec(input);
  if (fn) {
    const parts = fn[1].split(/[\s,/]+/).filter(Boolean);
    if (parts.length < 3) fail(`${where}: unparseable colour "${input}"`);
    const [r, g, b, a = "1"] = parts;
    return {
      r: Number.parseInt(r, 10),
      g: Number.parseInt(g, 10),
      b: Number.parseInt(b, 10),
      a: a.endsWith("%") ? Number.parseFloat(a) / 100 : Number.parseFloat(a),
    };
  }
  fail(`${where}: unsupported colour syntax "${input}"`);
  return { r: 0, g: 0, b: 1, a: 1 };
}

/** `#RRGGBB` when opaque, `rgba(r, g, b, a)` otherwise — the same colour, spelled for RN. */
function toRgbString({ r, g, b, a }, where) {
  if (a === 1) {
    /** @param {number} n */
    const hex = (n) => n.toString(16).padStart(2, "0");
    return `#${hex(r)}${hex(g)}${hex(b)}`.toUpperCase();
  }
  if (![r, g, b, a].every((n) => Number.isFinite(n))) fail(`${where}: non-finite channel`);
  return `rgba(${r}, ${g}, ${b}, ${Number.parseFloat(a.toFixed(4))})`;
}

const toChannels = ({ r, g, b }) => `${r} ${g} ${b}`;
/** Tauri `Color` accepts a hex string, so the frame colour is emitted as one. */
const toTauriHex = ({ r, g, b, a }) =>
  `#${[r, g, b]
    .map((n) => n.toString(16).padStart(2, "0"))
    .join("")
    .toUpperCase()}${a === 1 ? "" : Math.round(a * 255).toString(16).padStart(2, "0").toUpperCase()}`;
/** Tauri `Color` also accepts an RGBA array, which is what the window frame needs. */
const toRgbaArray = ({ r, g, b, a }) => [r, g, b, Math.round(a * 255)];

function parseUnit(value, unit, fallback) {
  const match = new RegExp(`^(-?[\\d.]+)${unit}$`).exec(String(value).trim());
  if (!match) {
    fail(`expected "${unit}" unit, received "${value}"`);
    return fallback;
  }
  return Number.parseFloat(match[1]);
}

// The desktop CSS layer expresses blur radius as a CSS length (`--mat-blur`),
// so there is no pixel->intensity conversion here. apps/mobile needs one because
// expo-blur takes a 0..100 dial instead of a radius.

// ---------------------------------------------------------------------------
// 3. Naming
// ---------------------------------------------------------------------------

function cssVar(key) {
  const kebab = key
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([a-zA-Z])(\d)/g, "$1-$2")
    .toLowerCase();
  return `--${kebab}`;
}

function tsKey(cssName) {
  const body = cssName.replace(/^--/, "");
  const camel = body.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(camel) ? camel : body.replace(/-/g, "_");
}

const CSS_VALUED_MATERIAL_KEYS = new Set([
  "mat-blur",
  "mat-saturate",
  "mat-brightness",
  "mat-translucent",
  "mat-border-alpha",
  "mat-specular",
  "mat-fresnel",
  "shadow-overlay",
  "shadow-sheet",
  "mat-filter",
]);
const COLOR_VALUED_MATERIAL_KEYS = new Set([
  "surface-overlay",
  "surface-nav",
  "surface-sheet",
  "surface-palette",
  "surface-scrim",
  "mat-native",
]);
for (const key of MATERIAL_KEYS) {
  if (!CSS_VALUED_MATERIAL_KEYS.has(key) && !COLOR_VALUED_MATERIAL_KEYS.has(key)) {
    fail(`material key "${key}" is neither CSS-typed nor a known colour role`);
  }
}

// ---------------------------------------------------------------------------
// 4. Emit: src/styles/tokens.css
// ---------------------------------------------------------------------------

const structureBlock = (palette) =>
  Object.entries(palette.structure)
    .map(([key, value]) => `  ${cssVar(key)}: ${value};`)
    .join("\n");

function rgbTripletBlock(palette) {
  const lines = [];
  for (const [key, value] of Object.entries(palette.structure)) {
    const channels = parseColor(value, `${palette.id}/${key}`);
    if (channels.a !== 1) continue;
    lines.push(`  ${cssVar(key)}-rgb: ${toChannels(channels)};`);
  }
  return lines;
}

const css = [];
css.push(`/* ${BANNER_LINES.join("\n * ")}`);
css.push(" *");
css.push(" * The custom-property NAMES are the contract: they are identical to");
css.push(" * packages/design-system/tokens.css so a value changed in one platform is");
css.push(" * visibly changed in all of them. Values are copied, never re-derived.");
css.push(" */");
css.push("");
const defaultPalette = palettes.find((p) => p.id === DEFAULT_PALETTE_ID);
css.push(":root {");
css.push(`  color-scheme: ${defaultPalette.tier};`);
css.push(structureBlock(defaultPalette));
css.push(...rgbTripletBlock(defaultPalette));
css.push("}");

for (const palette of palettes) {
  css.push("");
  css.push(`/* ${palette.name} — Figma scheme ${palette.figma.scheme} (${palette.figma.name}) */`);
  css.push(`[data-palette="${palette.id}"] {`);
  css.push(`  color-scheme: ${palette.tier};`);
  css.push(structureBlock(palette));
  css.push(...rgbTripletBlock(palette));
  css.push("}");
}

for (const palette of palettes) {
  for (const materialId of MATERIAL_IDS) {
    const layer = palette.materials[materialId];
    css.push("");
    css.push(`/* ${palette.name} · ${contract.materials[materialId].name} — material layer (text/accent inherited) */`);
    css.push(`[data-palette="${palette.id}"][data-material="${materialId}"] {`);
    for (const [key, value] of Object.entries(layer)) {
      if (CSS_VALUED_MATERIAL_KEYS.has(key)) {
        css.push(`  ${cssVar(key)}: ${value};`);
        continue;
      }
      const at = `${palette.id}/${materialId}/${key}`;
      const channels = parseColor(value, at);
      css.push(`  ${cssVar(key)}: ${toRgbString(channels, at)};`);
      if (channels.a === 1) css.push(`  ${cssVar(key)}-rgb: ${toChannels(channels)};`);
    }
    css.push("}");
  }
}

css.push("");
css.push("@media (prefers-reduced-transparency: reduce) {");
css.push("  /* Legibility before material: the paired -solid tokens (material-modes.md §2.6). */");
css.push("  [data-palette] {");
for (const [translucent] of SOLID_PAIRS) {
  css.push(`    ${cssVar(translucent)}: var(${cssVar(`${translucent}-solid`)});`);
}
css.push("    --mat-blur: 0px;");
css.push("    --mat-filter: none;");
css.push("  }");
css.push("}");
css.push("");
css.push("@media (prefers-contrast: more) {");
css.push("  [data-palette] {");
css.push("    --border-default: var(--border-strong);");
css.push("    --text-muted: var(--text-secondary);");
css.push("  }");
css.push("}");

// ---------------------------------------------------------------------------
// 5. Emit: src/theme/tokens.ts
// ---------------------------------------------------------------------------

const q = (value) => JSON.stringify(value);
const ts = [];
ts.push(`// ${BANNER_LINES.join("\n// ")}`);
ts.push("");
ts.push("/** Palette ids, in contract order. */");
ts.push(`export const PALETTE_IDS = [${palettes.map((p) => q(p.id)).join(", ")}] as const;`);
ts.push("export type PaletteId = (typeof PALETTE_IDS)[number];");
ts.push("");
ts.push("/** Material mode ids. Order is the shipped default order. */");
ts.push(`export const MATERIAL_IDS = [${MATERIAL_IDS.map(q).join(", ")}] as const;`);
ts.push("export type MaterialId = (typeof MATERIAL_IDS)[number];");
ts.push("");
ts.push('export type PaletteTier = "dark" | "light";');
ts.push("");
ts.push("export interface PaletteMeta {");
ts.push("  readonly id: PaletteId;");
ts.push("  readonly name: string;");
ts.push("  readonly tier: PaletteTier;");
ts.push("  readonly figmaScheme: number;");
ts.push("  readonly swatch: {");
ts.push("    readonly canvas: string;");
ts.push("    readonly raised: string;");
ts.push("    readonly accent: string;");
ts.push("  };");
ts.push("}");
ts.push("");
ts.push("export interface MaterialMeta {");
ts.push("  readonly id: MaterialId;");
ts.push("  readonly name: string;");
ts.push("  readonly blurb: string;");
ts.push("  readonly blurPx: number;");
ts.push("  readonly saturate: number;");
ts.push("  readonly brightness: number;");
ts.push("  readonly translucent: boolean;");
ts.push("}");
ts.push("");
ts.push("export interface ThemeColors {");
for (const key of STRUCTURE_KEYS) ts.push(`  readonly ${tsKey(cssVar(key))}: string;`);
ts.push("}");
ts.push("");
ts.push("export interface ThemeMaterial {");
ts.push("  readonly surfaceOverlay: string;");
ts.push("  readonly surfaceNav: string;");
ts.push("  readonly surfaceSheet: string;");
ts.push("  readonly surfacePalette: string;");
ts.push("  readonly surfaceScrim: string;");
ts.push("  readonly surfaceOverlaySolid: string;");
ts.push("  readonly surfaceNavSolid: string;");
ts.push("  readonly surfaceSheetSolid: string;");
ts.push("  readonly surfacePaletteSolid: string;");
ts.push("  readonly borderDefaultAlpha: number;");
ts.push("  readonly blurPx: number;");
ts.push("  readonly saturate: number;");
ts.push("  readonly brightness: number;");
ts.push("  readonly translucent: boolean;");
ts.push("  readonly specular: string;");
ts.push("  readonly fresnel: string;");
ts.push("  readonly shadowOverlay: string;");
ts.push("  readonly shadowSheet: string;");
ts.push("  /** `--mat-native`: the frame colour a native backdrop (Mica / vibrancy) takes. */");
ts.push("  readonly nativeFrame: string;");
ts.push("}");
ts.push("");
ts.push("export interface Theme {");
ts.push("  readonly paletteId: PaletteId;");
ts.push("  readonly materialId: MaterialId;");
ts.push("  readonly tier: PaletteTier;");
ts.push("  readonly colors: ThemeColors;");
ts.push("  readonly material: ThemeMaterial;");
ts.push("}");
ts.push("");
ts.push("/** Picker metadata — one entry per palette, swatches included. */");
ts.push("export const PALETTES: readonly PaletteMeta[] = [");
for (const palette of palettes) {
  const swatch = (key) =>
    toRgbString(parseColor(palette.structure[key], `${palette.id}/${key}`), `${palette.id}/${key}`);
  ts.push(
    `  { id: ${q(palette.id)}, name: ${q(palette.name)}, tier: ${q(palette.tier)}, ` +
      `figmaScheme: ${palette.figma.scheme}, swatch: { canvas: ${q(swatch("canvas"))}, ` +
      `raised: ${q(swatch("surfaceRaised"))}, accent: ${q(swatch("accentPrimary"))} } },`,
  );
}
ts.push("];");
ts.push("");
ts.push("/** Picker metadata — one entry per material mode. */");
ts.push("export const MATERIALS: readonly MaterialMeta[] = [");
for (const materialId of MATERIAL_IDS) {
  const meta = contract.materials[materialId];
  const sample = palettes[0].materials[materialId];
  ts.push(
    `  { id: ${q(materialId)}, name: ${q(meta.name)}, blurb: ${q(meta.blurb)}, ` +
      `blurPx: ${parseUnit(sample["mat-blur"], "px", 0)}, ` +
      `saturate: ${parseUnit(sample["mat-saturate"], "%", 100) / 100}, ` +
      `brightness: ${parseUnit(sample["mat-brightness"], "%", 100) / 100}, ` +
      `translucent: ${sample["mat-translucent"] === "1"} },`,
  );
}
ts.push("];");
ts.push("");
ts.push("const PALETTE_COLORS: Readonly<Record<PaletteId, ThemeColors>> = {");
for (const palette of palettes) {
  const entries = STRUCTURE_KEYS.map((key) => {
    const value = toRgbString(
      parseColor(palette.structure[key], `${palette.id}/${key}`),
      `${palette.id}/${key}`,
    );
    return `${tsKey(cssVar(key))}: ${q(value)}`;
  });
  ts.push(`  ${q(palette.id)}: { ${entries.join(", ")} },`);
}
ts.push("};");
ts.push("");
ts.push("const PALETTE_MATERIALS: Readonly<Record<PaletteId, Record<MaterialId, ThemeMaterial>>> = {");
for (const palette of palettes) {
  ts.push(`  ${q(palette.id)}: {`);
  for (const materialId of MATERIAL_IDS) {
    const layer = palette.materials[materialId];
    const at = `${palette.id}/${materialId}`;
    const color = (name) =>
      toRgbString(parseColor(layer[name], `${at}/${name}`), `${at}/${name}`);
    const solid = (name) =>
      toRgbString(parseColor(palette.structure[name], `${at}/${name}`), `${at}/${name}`);
    ts.push(
      `    ${q(materialId)}: {` +
        ` surfaceOverlay: ${q(color("surface-overlay"))}, ` +
        ` surfaceNav: ${q(color("surface-nav"))}, ` +
        ` surfaceSheet: ${q(color("surface-sheet"))}, ` +
        ` surfacePalette: ${q(color("surface-palette"))}, ` +
        ` surfaceScrim: ${q(color("surface-scrim"))}, ` +
        ` surfaceOverlaySolid: ${q(solid("surfaceOverlaySolid"))}, ` +
        ` surfaceNavSolid: ${q(solid("surfaceNavSolid"))}, ` +
        ` surfaceSheetSolid: ${q(solid("surfaceSheetSolid"))}, ` +
        ` surfacePaletteSolid: ${q(solid("surfacePaletteSolid"))}, ` +
        ` borderDefaultAlpha: ${parseUnit(layer["mat-border-alpha"], "", 1)}, ` +
        ` blurPx: ${parseUnit(layer["mat-blur"], "px", 0)}, ` +
        ` saturate: ${parseUnit(layer["mat-saturate"], "%", 100) / 100}, ` +
        ` brightness: ${parseUnit(layer["mat-brightness"], "%", 100) / 100}, ` +
        ` translucent: ${layer["mat-translucent"] === "1"}, ` +
        ` specular: ${q(layer["mat-specular"])}, ` +
        ` fresnel: ${q(layer["mat-fresnel"])}, ` +
        ` shadowOverlay: ${q(layer["shadow-overlay"])}, ` +
        ` shadowSheet: ${q(layer["shadow-sheet"])}, ` +
        ` nativeFrame: ${q(color("mat-native"))} ` +
        `},`,
    );
  }
  ts.push("  },");
}
ts.push("};");
ts.push("");
ts.push(`export const DEFAULT_PALETTE_ID: PaletteId = ${q(DEFAULT_PALETTE_ID)};`);
ts.push(`export const DEFAULT_MATERIAL_ID: MaterialId = ${q(DEFAULT_MATERIAL_ID)};`);
ts.push("");
ts.push("export function isPaletteId(value: string): value is PaletteId {");
ts.push("  return (PALETTE_IDS as readonly string[]).includes(value);");
ts.push("}");
ts.push("");
ts.push("export function isMaterialId(value: string): value is MaterialId {");
ts.push("  return (MATERIAL_IDS as readonly string[]).includes(value);");
ts.push("}");
ts.push("");
ts.push("/**");
ts.push(" * Resolve one palette + mode to runtime values. `reduceTransparency` swaps");
ts.push(" * the four translucent roles for their paired `-solid` tokens");
ts.push(" * (material-modes.md §2.6 Fallback 2) — which on desktop is also what");
ts.push(" * Linux gets unconditionally, because Tauri window effects are unsupported");
ts.push(" * there.");
ts.push(" */");
ts.push("export function resolveTheme(");
ts.push("  paletteId: PaletteId,");
ts.push("  materialId: MaterialId,");
ts.push("  reduceTransparency = false,");
ts.push("): Theme {");
ts.push("  const colors = PALETTE_COLORS[paletteId];");
ts.push("  const material = PALETTE_MATERIALS[paletteId][materialId];");
ts.push("  if (!colors || !material) {");
ts.push("    throw new Error(`UNKNOWN_THEME: ${paletteId}/${materialId} is not in tokens.json`);");
ts.push("  }");
ts.push("  const tier: PaletteTier = PALETTES.find((p) => p.id === paletteId)?.tier ?? \"dark\";");
ts.push("  if (!reduceTransparency) {");
ts.push("    return { paletteId, materialId, tier, colors, material };");
ts.push("  }");
ts.push("  return {");
ts.push("    paletteId,");
ts.push("    materialId,");
ts.push("    tier,");
ts.push("    colors,");
ts.push("    material: {");
ts.push("      ...material,");
ts.push("      surfaceOverlay: material.surfaceOverlaySolid,");
ts.push("      surfaceNav: material.surfaceNavSolid,");
ts.push("      surfaceSheet: material.surfaceSheetSolid,");
ts.push("      surfacePalette: material.surfacePaletteSolid,");
ts.push("      blurPx: 0,");
ts.push("      translucent: false,");
ts.push("      specular: \"none\",");
ts.push("      fresnel: \"none\",");
ts.push("    },");
ts.push("  };");
ts.push("}");

// ---------------------------------------------------------------------------
// 6. Emit: src/theme/native.ts — the Tauri window-effect mapping
// ---------------------------------------------------------------------------

/**
 * Which native window effect a material mode asks for, per platform.
 *
 * Fidelity, honestly stated (material-modes.md §4.3/§4.4/§4.7):
 *
 * - Windows: Mica. `mica` is Windows 11 only; Windows 10 has no Mica and Tauri
 *   offers no BaseAlt (BaseAlt is what material-modes §4.3 asks for), so acrylic
 *   and liquid-glass both resolve to `mica` and the difference between them is
 *   carried by the in-webview CSS material layer.
 * - macOS: NSVisualEffectView vibrancy through Tauri. AppKit has no Liquid Glass
 *   and Tauri exposes no `isEmphasized` or per-role material, so both modes
 *   resolve to `sidebar` — the material whose NSVisualEffectView.Material the
 *   sidebar actually is — again with the CSS layer carrying the difference.
 * - Linux: Tauri documents window effects as Unsupported. `null` means "fall
 *   back to the `-solid` tokens and the opaque window background", which is what
 *   tauri.linux.conf.json is generated to do.
 *
 * Rule: a window may carry ONE backdrop. Mica's own guidance is "Don't apply
 * backdrop material more than once in an application" (material-modes §3.1), so
 * this is window-level by construction and every in-webview material is CSS.
 */
const native = [];
native.push(`// ${BANNER_LINES.join("\n// ")}`);
native.push("");
native.push('import type { MaterialId } from "./tokens";');
native.push("");
native.push("/**");
native.push(" * The Tauri `WindowEffect` union, as published by");
native.push(" * @tauri-apps/cli config.schema.json (WindowEffect enum). Kept as a local");
native.push(" * type so this module never imports the Tauri runtime and stays usable");
native.push(" * from the generator's own validation.");
native.push(" */");
native.push("export type TauriWindowEffect =");
for (const effect of [
  "titlebar",
  "selection",
  "menu",
  "popover",
  "sidebar",
  "headerView",
  "sheet",
  "windowBackground",
  "hudWindow",
  "fullScreenUI",
  "tooltip",
  "contentBackground",
  "underWindowBackground",
  "underPageBackground",
  "mica",
  "micaDark",
  "micaLight",
  "tabbed",
  "tabbedDark",
  "tabbedLight",
  "blur",
  "acrylic",
]) {
  native.push(`  | "${effect}"`);
}
native.push("  | \"appearanceBased\";");
native.push("");
native.push('export type DesktopPlatform = "windows" | "macos" | "linux";');
native.push("");
native.push("export interface NativeMaterialMapping {");
native.push("  /** `null` = this platform cannot do a backdrop; use the `-solid` tokens. */");
native.push("  readonly effects: readonly TauriWindowEffect[] | null;");
native.push("  /** Whether the window must be transparent for the effect to be visible. */");
native.push("  readonly requiresTransparentWindow: boolean;");
native.push("  /** Why the mapping looks the way it does — surfaced in release notes. */");
native.push("  readonly fidelity: \"full\" | \"approximation\" | \"unsupported\";");
native.push("  readonly note: string;");
native.push("}");
native.push("");
native.push("export type NativeMaterialMap = Readonly<Record<MaterialId, Readonly<Record<DesktopPlatform, NativeMaterialMapping>>>>;");
native.push("");
native.push("export const NATIVE_MATERIALS: NativeMaterialMap = {");
const mapping = {
  minimal: {
    windows: {
      effect: null,
      note: "No backdrop. The opaque canvas token is the window background.",
      fidelity: "full",
    },
    macos: {
      effect: null,
      note: "No vibrancy. The opaque canvas token is the window background.",
      fidelity: "full",
    },
    linux: {
      effect: null,
      note: "Tauri window effects are unsupported on Linux — and Minimal asks for none, so the result is exact rather than degraded.",
      fidelity: "full",
    },
  },
  acrylic: {
    windows: {
      effect: "mica",
      note: "Mica (Windows 11). The native half of acrylic mode; the CSS material layer supplies the tint and blur in-webview.",
      fidelity: "approximation",
    },
    macos: {
      effect: "sidebar",
      note: "NSVisualEffectView sidebar vibrancy — the AppKit material whose documented use is a window sidebar, which is what this shell's rail is.",
      fidelity: "full",
    },
    linux: {
      effect: null,
      note: "Tauri window effects are unsupported on Linux: acrylic falls back to the -solid tokens.",
      fidelity: "unsupported",
    },
  },
  "liquid-glass": {
    windows: {
      effect: "mica",
      note: "Mica again — Tauri exposes neither MicaKind.BaseAlt nor MicaKind.Base, and AppKit has no Liquid Glass. Same native backdrop as acrylic; the CSS layer carries the difference.",
      fidelity: "approximation",
    },
    macos: {
      effect: "sidebar",
      note: "Same vibrancy material as acrylic — Tauri exposes no isEmphasized and AppKit has no Liquid Glass.",
      fidelity: "approximation",
    },
    linux: {
      effect: null,
      note: "Tauri window effects are unsupported on Linux: liquid glass falls back to the -solid tokens.",
      fidelity: "unsupported",
    },
  },
};
for (const materialId of MATERIAL_IDS) {
  native.push(`  ${q(materialId)}: {`);
  for (const [platform, { effect, note, fidelity }] of Object.entries(mapping[materialId])) {
    const effects = effect === null ? "null" : `[${q(effect)}]`;
    const transparent = effect === null ? "false" : "true";
    native.push(
      `    ${platform}: { effects: ${effects}, requiresTransparentWindow: ${transparent}, fidelity: ${q(fidelity)}, note: ${q(note)} },`,
    );
  }
  native.push("  },");
}
native.push("};");
native.push("");
native.push("/**");
native.push(" * Resolve the window effect for a material on this platform. `null` is a");
native.push(" * first-class answer: it means the caller must paint the `-solid` tokens.");
native.push(" */");
native.push("export function nativeMaterialFor(");
native.push("  materialId: MaterialId,");
native.push("  platform: DesktopPlatform,");
native.push("): NativeMaterialMapping {");
native.push("  return NATIVE_MATERIALS[materialId][platform];");
native.push("}");

// ---------------------------------------------------------------------------
// 7. Emit: the three platform Tauri configs
//
// STRICT JSON, no comments. Tauri parses `*.json` with serde_json; only
// `*.json5` is parsed as JSON5, and these files must keep the `.json` name the
// platform-override lookup requires. Provenance for these files lives in
// apps/desktop/scripts/generate-tokens.mjs and in
// docs/design/platform-tokens.md §5, not in a comment that could break the build.
// ---------------------------------------------------------------------------

const frameRgba = toRgbaArray(parseColor(defaultPalette.materials[DEFAULT_MATERIAL_ID]["mat-native"], "mat-native"));
const frameHex = toTauriHex(parseColor(defaultPalette.materials[DEFAULT_MATERIAL_ID]["mat-native"], "mat-native"));

/**
 * The window block is written out in FULL on purpose. Tauri merges the
 * platform-specific file with the base config; whether that merge is a
 * deep-object merge or an array replace, a complete window object gives the
 * same result either way. A partial override would silently drop
 * width/height/titleBarStyle on one of the two interpretations.
 */
const baseWindow = {
  label: "main",
  title: "Buddysaradhi",
  width: 1440,
  height: 900,
  minWidth: 1024,
  minHeight: 600,
  resizable: true,
  fullscreen: false,
  center: true,
  theme: "Dark",
  titleBarStyle: "Overlay",
  hiddenTitle: true,
  decorations: true,
};

const windowsConf = {
  app: {
    windows: [
      {
        ...baseWindow,
        // Tauri: "Requires the window to be transparent."
        transparent: true,
        backgroundColor: frameRgba,
        windowEffects: { effects: ["mica"] },
      },
    ],
  },
};

const macosConf = {
  app: {
    // Required for `transparent: true` on macOS. It uses private APIs, so the
    // desktop app cannot be submitted to the Mac App Store with this on — the
    // trade is recorded in docs/design/platform-tokens.md §5.
    macOSPrivateApi: true,
    windows: [
      {
        ...baseWindow,
        transparent: true,
        backgroundColor: frameRgba,
        windowEffects: {
          effects: ["sidebar"],
          state: "followsWindowActiveState",
          radius: 12,
        },
      },
    ],
  },
};

const linuxConf = {
  app: {
    windows: [
      {
        ...baseWindow,
        // No windowEffects key at all: Tauri documents them as unsupported on
        // Linux, so this platform falls back to the `-solid` tokens and an
        // opaque frame. Explicit rather than accidental.
        transparent: false,
        backgroundColor: frameRgba,
      },
    ],
  },
};

// ---------------------------------------------------------------------------
// 8. Write (only now, after every check has passed)
// ---------------------------------------------------------------------------

if (problems.length > 0) {
  process.stderr.write("FATAL: colour values in the contract could not be parsed:\n");
  for (const problem of problems) process.stderr.write(`  - ${problem}\n`);
  process.exit(1);
}

mkdirSync(join(appRoot, "src", "styles"), { recursive: true });
mkdirSync(join(appRoot, "src", "theme"), { recursive: true });
writeFileSync(join(appRoot, "src", "styles", "tokens.css"), `${css.join("\n")}\n`, "utf8");
writeFileSync(join(appRoot, "src", "theme", "tokens.ts"), `${ts.join("\n")}\n`, "utf8");
writeFileSync(join(appRoot, "src", "theme", "native.ts"), `${native.join("\n")}\n`, "utf8");

const tauriRoot = join(appRoot, "src-tauri");
writeFileSync(
  join(tauriRoot, "tauri.windows.conf.json"),
  `${JSON.stringify(windowsConf, null, 2)}\n`,
  "utf8",
);
writeFileSync(
  join(tauriRoot, "tauri.macos.conf.json"),
  `${JSON.stringify(macosConf, null, 2)}\n`,
  "utf8",
);
writeFileSync(
  join(tauriRoot, "tauri.linux.conf.json"),
  `${JSON.stringify(linuxConf, null, 2)}\n`,
  "utf8",
);

process.stdout.write(
  [
    `contract:   ${contractPath}`,
    `version:    ${contract.version} (${palettes.length} palettes x ${MATERIAL_IDS.length} materials)`,
    `frame:      ${frameHex} = [${frameRgba.join(", ")}]`,
    `wrote:      ${join(appRoot, "src", "styles", "tokens.css")}`,
    `wrote:      ${join(appRoot, "src", "theme", "tokens.ts")}`,
    `wrote:      ${join(appRoot, "src", "theme", "native.ts")}`,
    `wrote:      ${join(tauriRoot, "tauri.windows.conf.json")}`,
    `wrote:      ${join(tauriRoot, "tauri.macos.conf.json")}`,
    `wrote:      ${join(tauriRoot, "tauri.linux.conf.json")}`,
    "",
  ].join("\n"),
);