// Implements: docs/design/overhaul-plan.md §6 — NativeWind/Expo token wiring.
//
// WHY A GENERATOR AND NOT A COPY
// `packages/design-system/tokens.json` is the platform contract (overhaul-plan
// §2.2). 20 palettes x 3 material modes is 1 900+ colour values. Hand-copying
// them is how a token system dies: the copy drifts, nobody notices, and two
// platforms quietly disagree about what "warning" means. This script is the only
// thing allowed to turn the contract into app files, and it writes a DO NOT EDIT
// banner into every artefact it produces.
//
// INPUT RESOLUTION (documented per the W5 brief)
// `apps/mobile` does NOT declare `@buddysaradhi/design-system` as a dependency,
// so the workspace package is not resolvable from `apps/mobile/node_modules`
// (verified: `apps/mobile/node_modules/@buddysaradhi` does not exist). The
// contract is therefore read through a path relative to this file:
//   apps/mobile/scripts/../../.. -> repo root -> packages/design-system/tokens.json
// If the workspace package is ever linked (add it to package.json dependencies
// and run `pnpm install`), the `require.resolve` branch below takes over and the
// relative path becomes dead — no other change is needed.
//
// RUN
//   node apps/mobile/scripts/generate-tokens.mjs
//
// OUTPUTS (all generated, all DO NOT EDIT)
//   apps/mobile/tokens.css                    custom properties, same names as
//                                             packages/design-system/tokens.css,
//                                             plus `-rgb` channel triplets so the
//                                             Tailwind/NativeWind opacity modifier
//                                             (`bg-accent/20`) keeps working
//   apps/mobile/tailwind-theme.generated.js   the Tailwind/NativeWind theme scale,
//                                             every colour a `var()` reference
//   apps/mobile/src/theme/tokens.ts           typed runtime module: palette list,
//                                             material list, RN-safe colour values
//
// FAIL-CLOSED
// Any shape/contract problem exits 1 and writes NOTHING, so a broken contract can
// never reach a device (AGENTS.md Rule 9 — no silent failures).
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const appRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = join(appRoot, "..", "..");

const BANNER_LINES = [
  "GENERATED by apps/mobile/scripts/generate-tokens.mjs — DO NOT EDIT.",
  "Source:    packages/design-system/tokens.json (the platform contract)",
  "Regenerate: node apps/mobile/scripts/generate-tokens.mjs",
  "Verify:     pnpm --filter @buddysaradhi/design-system verify",
  "Spec:       docs/design/overhaul-plan.md §6",
];

// ---------------------------------------------------------------------------
// 1. Read the contract
// ---------------------------------------------------------------------------

function resolveContractPath() {
  try {
    return require.resolve("@buddysaradhi/design-system/tokens.json");
  } catch {
    return join(repoRoot, "packages", "design-system", "tokens.json");
  }
}

const contractPath = resolveContractPath();
let contract;
try {
  contract = JSON.parse(readFileSync(contractPath, "utf8"));
} catch (cause) {
  process.stderr.write(`FATAL: cannot read the token contract at ${contractPath}\n`);
  process.stderr.write(`       ${cause instanceof Error ? cause.message : String(cause)}\n`);
  process.exit(1);
}

const problems = [];
const fail = (message) => problems.push(message);

// ---------------------------------------------------------------------------
// 2. Validate the shape we depend on (fail closed)
// ---------------------------------------------------------------------------

const MATERIAL_IDS = ["minimal", "acrylic", "liquid-glass"];
const DEFAULT_PALETTE_ID = "inked";
const DEFAULT_MATERIAL_ID = "minimal";

if (!Array.isArray(contract.palettes) || contract.palettes.length === 0) {
  fail("tokens.json has no `palettes` array");
}
for (const id of MATERIAL_IDS) {
  if (!contract.materials || !contract.materials[id]) fail(`tokens.json is missing material "${id}"`);
}

const palettes = Array.isArray(contract.palettes) ? contract.palettes : [];
const STRUCTURE_KEYS = palettes.length > 0 ? Object.keys(palettes[0].structure ?? {}) : [];
const MATERIAL_KEYS =
  palettes.length > 0 ? Object.keys(palettes[0].materials?.[DEFAULT_MATERIAL_ID] ?? {}) : [];

/** Solid fallbacks that exist in `structure` and pair with a translucent role. */
const SOLID_PAIRS = [
  ["surface-overlay", "surfaceOverlaySolid"],
  ["surface-nav", "surfaceNavSolid"],
  ["surface-sheet", "surfaceSheetSolid"],
  ["surface-palette", "surfacePaletteSolid"],
];

const seenIds = new Set();
for (const palette of palettes) {
  for (const field of ["id", "name", "tier", "figma", "structure", "materials"]) {
    if (palette[field] === undefined) fail(`palette is missing "${field}"`);
  }
  if (seenIds.has(palette.id)) fail(`duplicate palette id "${palette.id}"`);
  seenIds.add(palette.id);

  const structureKeys = Object.keys(palette.structure ?? {});
  if (structureKeys.join(",") !== STRUCTURE_KEYS.join(",")) {
    fail(`palette "${palette.id}" has a different structure key set than "${palettes[0].id}"`);
  }
  for (const id of MATERIAL_IDS) {
    const layer = palette.materials?.[id];
    if (!layer) {
      fail(`palette "${palette.id}" is missing material "${id}"`);
      continue;
    }
    const layerKeys = Object.keys(layer);
    if (layerKeys.join(",") !== MATERIAL_KEYS.join(",")) {
      fail(`palette "${palette.id}" material "${id}" has a different key set`);
    }
    for (const [translucent, solidKey] of SOLID_PAIRS) {
      if (!layer[translucent]) fail(`palette "${palette.id}" material "${id}" lacks "${translucent}"`);
      if (!palette.structure?.[solidKey]) {
        fail(`palette "${palette.id}" lacks the paired fallback "${solidKey}"`);
      }
    }
  }
}
if (palettes.length > 0 && !seenIds.has(DEFAULT_PALETTE_ID)) {
  fail(`default palette "${DEFAULT_PALETTE_ID}" is not in the contract`);
}
if (palettes.length > 0 && STRUCTURE_KEYS.length === 0) fail("structure key set is empty");

if (problems.length > 0) {
  process.stderr.write("FATAL: token contract does not satisfy what this generator needs:\n");
  for (const problem of problems) process.stderr.write(`  - ${problem}\n`);
  process.exit(1);
}

// ---------------------------------------------------------------------------
// 3. Colour maths — format conversion only, never a value decision
// ---------------------------------------------------------------------------

/** `#RGB` | `#RRGGBB` | `rgb(r g b / a)` | `rgba(r, g, b, a)` -> channels. */
function parseColor(value, where) {
  const input = String(value).trim();
  const hex = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(input);
  if (hex) {
    const body = hex[1];
    const full =
      body.length === 3
        ? body
            .split("")
            .map((c) => c + c)
            .join("")
        : body;
    return {
      r: Number.parseInt(full.slice(0, 2), 16),
      g: Number.parseInt(full.slice(2, 4), 16),
      b: Number.parseInt(full.slice(4, 6), 16),
      a: 1,
    };
  }
  const fn = /^rgba?\(([^)]+)\)$/i.exec(input);
  if (fn) {
    const parts = fn[1].split(/[\s,/]+/).filter(Boolean);
    if (parts.length < 3) fail(`${where}: unparseable colour "${input}"`);
    const [r, g, b, a = "1"] = parts;
    return {
      r: Number.parseInt(r, 10),
      g: Number.parseInt(g, 10),
      b: Number.parseInt(b, 10),
      a: a.endsWith("%") ? Number.parseFloat(a) / 100 : Number.parseFloat(a),
    };
  }
  fail(`${where}: unsupported colour syntax "${input}"`);
  return { r: 0, g: 0, b: 1, a: 1 };
}

/**
 * React Native's colour parser wants `#RRGGBB` or `rgba(r, g, b, a)`. The
 * contract emits CSS Color 4 `rgb(r g b / a)`, which RN does not accept, so the
 * alpha is re-expressed in the comma form. Same colour, RN-safe spelling.
 */
function toRgbString({ r, g, b, a }, where) {
  if (a === 1) {
    /** @param {number} n */
    const hex = (n) => n.toString(16).padStart(2, "0");
    return `#${hex(r)}${hex(g)}${hex(b)}`.toUpperCase();
  }
  if (![r, g, b, a].every((n) => Number.isFinite(n))) fail(`${where}: non-finite channel`);
  return `rgba(${r}, ${g}, ${b}, ${Number.parseFloat(a.toFixed(4))})`;
}

const toHex = (channels, where) => toRgbString(channels, where);
const toChannels = ({ r, g, b }) => `${r} ${g} ${b}`;

/** `48px` -> 48 ; `150%` -> 1.5 */
function parseUnit(value, unit, fallback) {
  const match = new RegExp(`^(-?[\\d.]+)${unit}$`).exec(String(value).trim());
  if (!match) {
    fail(`expected "${unit}" unit, received "${value}"`);
    return fallback;
  }
  return Number.parseFloat(match[1]);
}

/**
 * expo-blur's `intensity` is a 0..100 dial, not a pixel radius, so the CSS
 * radius has to be re-expressed. Same honesty note as material-modes.md §2.9 for
 * the CSS blur value: a tuned port, computed once here rather than per render.
 */
const BLUR_INTENSITY_CEILING_PX = 50;
const blurPxToIntensity = (px) => Math.round((Math.min(px, BLUR_INTENSITY_CEILING_PX) / BLUR_INTENSITY_CEILING_PX) * 100);

// ---------------------------------------------------------------------------
// 4. Naming
// ---------------------------------------------------------------------------

/** camelCase token key -> kebab CSS custom property (design-system §index.ts). */
function cssVar(key) {
  const kebab = key
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([a-zA-Z])(\d)/g, "$1-$2")
    .toLowerCase();
  return `--${kebab}`;
}

/** `--surface-raised` -> `surfaceRaised`, for the TS surface. */
function tsKey(cssName) {
  const body = cssName.replace(/^--/, "");
  const camel = body.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(camel) ? camel : body.replace(/-/g, "_");
}

/**
 * Semantic colour scale exposed to NativeWind/Tailwind. Every entry is a
 * `var()` reference to the contract name — a literal here is the failure mode
 * this whole wave exists to prevent.
 *
 * `fg-*` (not `text-*`) because a colour named `text-primary` would produce the
 * utility `text-text-primary`; these names are shared with apps/desktop so the
 * two platforms read the same vocabulary.
 */
const COLOR_SCALE = {
  canvas: "--canvas",
  surface: "--surface-raised",
  "surface-raised": "--surface-raised",
  "surface-inset": "--surface-inset",
  "surface-row": "--surface-row",
  "surface-sunken": "--surface-sunken",
  "surface-overlay-solid": "--surface-overlay-solid",
  "surface-nav-solid": "--surface-nav-solid",
  "surface-sheet-solid": "--surface-sheet-solid",
  "surface-palette-solid": "--surface-palette-solid",
  "surface-scrim": "--surface-scrim",
  hairline: "--border-default",
  edge: "--border-strong",
  "focus-ring": "--border-focus",
  "fg-primary": "--text-primary",
  "fg-secondary": "--text-secondary",
  "fg-muted": "--text-muted",
  "fg-inverse": "--text-inverse",
  accent: "--accent-primary",
  "accent-text": "--accent-text",
  "accent-on": "--accent-on-primary",
  success: "--success",
  info: "--info",
  warning: "--warning",
  danger: "--danger",
  "status-paid": "--status-paid",
  "status-partial": "--status-partial",
  "status-unpaid": "--status-unpaid",
  "status-overdue": "--status-overdue",
  "chart-1": "--chart-1",
  "chart-2": "--chart-2",
  "chart-3": "--chart-3",
  "chart-4": "--chart-4",
  "chart-5": "--chart-5",
  "chart-6": "--chart-6",
};

for (const [scaleName, contractName] of Object.entries(COLOR_SCALE)) {
  const key = Object.keys(palettes[0].structure).find((k) => cssVar(k) === contractName);
  if (!key) fail(`COLOR_SCALE["${scaleName}"] -> ${contractName} is not a structure role`);
}

/**
 * Material keys that carry a CSS-typed value (length, percentage, shadow,
 * filter). They are copied verbatim; only the colour keys are re-spelled.
 */
const CSS_VALUED_MATERIAL_KEYS = new Set([
  "mat-blur",
  "mat-saturate",
  "mat-brightness",
  "mat-translucent",
  "mat-border-alpha",
  "mat-specular",
  "mat-fresnel",
  "shadow-overlay",
  "shadow-sheet",
  "mat-filter",
]);
const COLOR_VALUED_MATERIAL_KEYS = new Set([
  "surface-overlay",
  "surface-nav",
  "surface-sheet",
  "surface-palette",
  "surface-scrim",
  "mat-native",
]);
for (const key of MATERIAL_KEYS) {
  const known =
    CSS_VALUED_MATERIAL_KEYS.has(key) || COLOR_VALUED_MATERIAL_KEYS.has(key);
  if (!known) fail(`material key "${key}" is neither CSS-typed nor a known colour role`);
}

// ---------------------------------------------------------------------------
// 5. Emit: tokens.css
// ---------------------------------------------------------------------------

const structureBlock = (palette) =>
  Object.entries(palette.structure)
    .map(([key, value]) => `  ${cssVar(key)}: ${value};`)
    .join("\n");

/** Opaque roles also get an `-rgb` channel triplet for the `/alpha` modifier. */
function rgbTripletBlock(palette) {
  const lines = [];
  for (const [key, value] of Object.entries(palette.structure)) {
    const channels = parseColor(value, `${palette.id}/${key}`);
    if (channels.a !== 1) continue;
    lines.push(`  ${cssVar(key)}-rgb: ${toChannels(channels)};`);
  }
  return lines;
}

const css = [];
css.push(`/* ${BANNER_LINES.join("\n * ")}`);
css.push(" *");
css.push(" * The custom-property NAMES are the contract: they are identical to");
css.push(" * packages/design-system/tokens.css so a value changed in one platform is");
css.push(" * visibly changed in all of them. Values are copied, never re-derived.");
css.push(" */");
css.push("");
const defaultPalette = palettes.find((p) => p.id === DEFAULT_PALETTE_ID);
css.push(`:root {`);
css.push(`  color-scheme: ${defaultPalette.tier};`);
css.push(structureBlock(defaultPalette));
css.push(...rgbTripletBlock(defaultPalette));
css.push("}");

for (const palette of palettes) {
  css.push("");
  css.push(`/* ${palette.name} — Figma scheme ${palette.figma.scheme} (${palette.figma.name}) */`);
  css.push(`[data-palette="${palette.id}"] {`);
  css.push(`  color-scheme: ${palette.tier};`);
  css.push(structureBlock(palette));
  css.push(...rgbTripletBlock(palette));
  css.push("}");
}

for (const palette of palettes) {
  for (const materialId of MATERIAL_IDS) {
    const layer = palette.materials[materialId];
    css.push("");
    css.push(
      `/* ${palette.name} · ${contract.materials[materialId].name} — material layer (text/accent inherited) */`,
    );
    css.push(`[data-palette="${palette.id}"][data-material="${materialId}"] {`);
    for (const [key, value] of Object.entries(layer)) {
      if (CSS_VALUED_MATERIAL_KEYS.has(key)) {
        // Lengths, percentages, shadows and `var()`-bearing filter strings are
        // copied verbatim; they resolve against the property block above.
        css.push(`  ${cssVar(key)}: ${value};`);
        continue;
      }
      const at = `${palette.id}/${materialId}/${key}`;
      const channels = parseColor(value, at);
      css.push(`  ${cssVar(key)}: ${toRgbString(channels, at)};`);
      if (channels.a === 1) {
        css.push(`  ${cssVar(key)}-rgb: ${toChannels(channels)};`);
      }
    }
    css.push("}");
  }
}

css.push("");
css.push("@media (prefers-reduced-transparency: reduce) {");
css.push("  /* Legibility before material: the paired -solid tokens (material-modes.md §2.6). */");
css.push("  [data-palette] {");
for (const [translucent] of SOLID_PAIRS) {
  css.push(`    ${cssVar(translucent)}: var(${cssVar(`${translucent}-solid`)});`);
}
css.push("    --mat-blur: 0px;");
css.push("    --mat-filter: none;");
css.push("  }");
css.push("}");
css.push("");
css.push("@media (prefers-contrast: more) {");
css.push("  [data-palette] {");
css.push("    --border-default: var(--border-strong);");
css.push("    --text-muted: var(--text-secondary);");
css.push("  }");
css.push("}");

// ---------------------------------------------------------------------------
// 6. Emit: tailwind-theme.generated.js (CJS — tailwind.config.js is CJS)
// ---------------------------------------------------------------------------

const themeLines = [];
themeLines.push(`/* ${BANNER_LINES.join("\n * ")} */`);
themeLines.push("");
themeLines.push("const rgb = (name) => `rgb(var(${name}-rgb) / <alpha-value>)`;");
themeLines.push("");
themeLines.push("/** Semantic colour scale. No literal value: each entry is the contract. */");
themeLines.push("const colors = {");
for (const [scaleName, contractName] of Object.entries(COLOR_SCALE)) {
  themeLines.push(`  "${scaleName}": rgb("${contractName}"),`);
}
themeLines.push("};");
themeLines.push("");
themeLines.push("/** Material roles as flat colours; shadows stay CSS strings (web/expo-web). */");
themeLines.push("const materialColors = {");
for (const [translucent] of SOLID_PAIRS) {
  const contractName = cssVar(translucent);
  themeLines.push(`  "${translucent}": rgb("${contractName}"),`);
  themeLines.push(`  "${translucent}-solid": rgb("${contractName}-solid"),`);
}
themeLines.push("};");
themeLines.push("");
themeLines.push("module.exports = {");
themeLines.push("  colors: { ...colors, ...materialColors },");
themeLines.push("  borderColor: {");
themeLines.push("    DEFAULT: rgb(\"--border-default\"),");
themeLines.push("    hairline: rgb(\"--border-default\"),");
themeLines.push("    edge: rgb(\"--border-strong\"),");
themeLines.push("    focus: rgb(\"--border-focus\"),");
themeLines.push("  },");
themeLines.push("  boxShadow: {");
themeLines.push("    overlay: \"var(--shadow-overlay)\",");
themeLines.push("    sheet: \"var(--shadow-sheet)\",");
themeLines.push("  },");
themeLines.push("};");

// ---------------------------------------------------------------------------
// 7. Emit: src/theme/tokens.ts
// ---------------------------------------------------------------------------

const q = (value) => JSON.stringify(value);
const tsLines = [];
tsLines.push(`// ${BANNER_LINES.join("\n// ")}`);
tsLines.push("");
tsLines.push("/** Palette ids, in contract order. */");
tsLines.push(`export const PALETTE_IDS = [${palettes.map((p) => q(p.id)).join(", ")}] as const;`);
tsLines.push("export type PaletteId = (typeof PALETTE_IDS)[number];");
tsLines.push("");
tsLines.push("/** Material mode ids. Order is the shipped default order. */");
tsLines.push(`export const MATERIAL_IDS = [${MATERIAL_IDS.map(q).join(", ")}] as const;`);
tsLines.push("export type MaterialId = (typeof MATERIAL_IDS)[number];");
tsLines.push("");
tsLines.push('/** Contrast tier of a palette — also the expo-blur tint it needs. */');
tsLines.push('export type PaletteTier = "dark" | "light";');
tsLines.push('/** expo-blur `tint` values. Derived from the palette tier, never hand-picked. */');
tsLines.push('export type MaterialTint = "dark" | "light" | "default";');
tsLines.push("");
tsLines.push("export interface PaletteMeta {");
tsLines.push("  readonly id: PaletteId;");
tsLines.push("  readonly name: string;");
tsLines.push("  readonly tier: PaletteTier;");
tsLines.push("  readonly figmaScheme: number;");
tsLines.push("  readonly swatch: {");
tsLines.push("    readonly canvas: string;");
tsLines.push("    readonly raised: string;");
tsLines.push("    readonly accent: string;");
tsLines.push("  };");
tsLines.push("}");
tsLines.push("");
tsLines.push("export interface MaterialMeta {");
tsLines.push("  readonly id: MaterialId;");
tsLines.push("  readonly name: string;");
tsLines.push("  readonly blurb: string;");
tsLines.push("  readonly blurPx: number;");
tsLines.push("  readonly blurIntensity: number;");
tsLines.push("  readonly saturate: number;");
tsLines.push("  readonly brightness: number;");
tsLines.push("  readonly translucent: boolean;");
tsLines.push("  readonly tint: MaterialTint;");
tsLines.push("}");
tsLines.push("");
tsLines.push("/** Every structural role, in React-Native-safe colour spelling. */");
tsLines.push("export interface ThemeColors {");
for (const key of STRUCTURE_KEYS) {
  tsLines.push(`  readonly ${tsKey(cssVar(key))}: string;`);
}
tsLines.push("}");
tsLines.push("");
tsLines.push("/** The material layer for one palette + mode. */");
tsLines.push("export interface ThemeMaterial {");
tsLines.push("  readonly surfaceOverlay: string;");
tsLines.push("  readonly surfaceNav: string;");
tsLines.push("  readonly surfaceSheet: string;");
tsLines.push("  readonly surfacePalette: string;");
tsLines.push("  readonly surfaceScrim: string;");
tsLines.push("  readonly surfaceOverlaySolid: string;");
tsLines.push("  readonly surfaceNavSolid: string;");
tsLines.push("  readonly surfaceSheetSolid: string;");
tsLines.push("  readonly surfacePaletteSolid: string;");
tsLines.push("  readonly borderDefaultAlpha: number;");
tsLines.push("  readonly blurPx: number;");
tsLines.push("  readonly blurIntensity: number;");
tsLines.push("  readonly saturate: number;");
tsLines.push("  readonly brightness: number;");
tsLines.push("  readonly translucent: boolean;");
tsLines.push("  readonly tint: MaterialTint;");
tsLines.push("  /** CSS-only: the specular hairline and fresnel sheen (material-modes.md §2.4). */");
tsLines.push("  readonly specular: string;");
tsLines.push("  readonly fresnel: string;");
tsLines.push("  readonly shadowOverlay: string;");
tsLines.push("  readonly shadowSheet: string;");
tsLines.push("  /** `--mat-native`: the frame colour a native backdrop takes (Mica/vibrancy). */");
tsLines.push("  readonly nativeFrame: string;");
tsLines.push("}");
tsLines.push("");
tsLines.push("export interface Theme {");
tsLines.push("  readonly paletteId: PaletteId;");
tsLines.push("  readonly materialId: MaterialId;");
tsLines.push("  readonly tier: PaletteTier;");
tsLines.push("  readonly colors: ThemeColors;");
tsLines.push("  readonly material: ThemeMaterial;");
tsLines.push("}");
tsLines.push("");
tsLines.push("/** Picker metadata — one entry per palette, swatches included. */");
tsLines.push("export const PALETTES: readonly PaletteMeta[] = [");
for (const palette of palettes) {
  const swatch = (key) =>
    toHex(parseColor(palette.structure[key], `${palette.id}/${key}`), `${palette.id}/${key}`);
  tsLines.push(
    `  { id: ${q(palette.id)}, name: ${q(palette.name)}, tier: ${q(palette.tier)}, ` +
      `figmaScheme: ${palette.figma.scheme}, swatch: { canvas: ${q(swatch("canvas"))}, ` +
      `raised: ${q(swatch("surfaceRaised"))}, accent: ${q(swatch("accentPrimary"))} } },`,
  );
}
tsLines.push("];");
tsLines.push("");
tsLines.push("/** Picker metadata — one entry per material mode. */");
tsLines.push("export const MATERIALS: readonly MaterialMeta[] = [");
for (const materialId of MATERIAL_IDS) {
  const meta = contract.materials[materialId];
  const sample = palettes[0].materials[materialId];
  const blurPx = parseUnit(sample["mat-blur"], "px", 0);
  const translucent = sample["mat-translucent"] === "1";
  tsLines.push(
    `  { id: ${q(materialId)}, name: ${q(meta.name)}, blurb: ${q(meta.blurb)}, ` +
      `blurPx: ${blurPx}, blurIntensity: ${translucent ? blurPxToIntensity(blurPx) : 0}, ` +
      `saturate: ${parseUnit(sample["mat-saturate"], "%", 1) / 100}, ` +
      `brightness: ${parseUnit(sample["mat-brightness"], "%", 1) / 100}, ` +
      `translucent: ${translucent}, tint: "default" },`,
  );
}
tsLines.push("];");
tsLines.push("");
tsLines.push("const PALETTE_COLORS: Readonly<Record<PaletteId, ThemeColors>> = {");
for (const palette of palettes) {
  const entries = STRUCTURE_KEYS.map((key) => {
    const value = toHex(
      parseColor(palette.structure[key], `${palette.id}/${key}`),
      `${palette.id}/${key}`,
    );
    return `${tsKey(cssVar(key))}: ${q(value)}`;
  });
  tsLines.push(`  ${q(palette.id)}: { ${entries.join(", ")} },`);
}
tsLines.push("};");
tsLines.push("");
tsLines.push("const PALETTE_MATERIALS: Readonly<Record<PaletteId, Record<MaterialId, ThemeMaterial>>> = {");
for (const palette of palettes) {
  tsLines.push(`  ${q(palette.id)}: {`);
  for (const materialId of MATERIAL_IDS) {
    const layer = palette.materials[materialId];
    const at = `${palette.id}/${materialId}`;
    const color = (name) => toHex(parseColor(layer[name], `${at}/${name}`), `${at}/${name}`);
    const solid = (name) => toHex(parseColor(palette.structure[name], `${at}/${name}`), `${at}/${name}`);
    const blurPx = parseUnit(layer["mat-blur"], "px", 0);
    const translucent = layer["mat-translucent"] === "1";
    tsLines.push(
      `    ${q(materialId)}: {` +
        ` surfaceOverlay: ${q(color("surface-overlay"))}, ` +
        ` surfaceNav: ${q(color("surface-nav"))}, ` +
        ` surfaceSheet: ${q(color("surface-sheet"))}, ` +
        ` surfacePalette: ${q(color("surface-palette"))}, ` +
        ` surfaceScrim: ${q(color("surface-scrim"))}, ` +
        ` surfaceOverlaySolid: ${q(solid("surfaceOverlaySolid"))}, ` +
        ` surfaceNavSolid: ${q(solid("surfaceNavSolid"))}, ` +
        ` surfaceSheetSolid: ${q(solid("surfaceSheetSolid"))}, ` +
        ` surfacePaletteSolid: ${q(solid("surfacePaletteSolid"))}, ` +
        ` borderDefaultAlpha: ${parseUnit(layer["mat-border-alpha"], "", 1)}, ` +
        ` blurPx: ${blurPx}, ` +
        ` blurIntensity: ${translucent ? blurPxToIntensity(blurPx) : 0}, ` +
        ` saturate: ${parseUnit(layer["mat-saturate"], "%", 100) / 100}, ` +
        ` brightness: ${parseUnit(layer["mat-brightness"], "%", 100) / 100}, ` +
        ` translucent: ${translucent}, ` +
        ` tint: ${q(palette.tier)}, ` +
        ` specular: ${q(layer["mat-specular"])}, ` +
        ` fresnel: ${q(layer["mat-fresnel"])}, ` +
        ` shadowOverlay: ${q(layer["shadow-overlay"])}, ` +
        ` shadowSheet: ${q(layer["shadow-sheet"])}, ` +
        ` nativeFrame: ${q(toHex(parseColor(layer["mat-native"], `${at}/mat-native`), at))} ` +
        `},`,
    );
  }
  tsLines.push("  },");
}
tsLines.push("};");
tsLines.push("");
tsLines.push(`export const DEFAULT_PALETTE_ID: PaletteId = ${q(DEFAULT_PALETTE_ID)};`);
tsLines.push(`export const DEFAULT_MATERIAL_ID: MaterialId = ${q(DEFAULT_MATERIAL_ID)};`);
tsLines.push("");
tsLines.push("export function isPaletteId(value: string): value is PaletteId {");
tsLines.push("  return (PALETTE_IDS as readonly string[]).includes(value);");
tsLines.push("}");
tsLines.push("");
tsLines.push("export function isMaterialId(value: string): value is MaterialId {");
tsLines.push("  return (MATERIAL_IDS as readonly string[]).includes(value);");
tsLines.push("}");
tsLines.push("");
tsLines.push("/**");
tsLines.push(" * Resolve one palette + mode to runtime values. No derivation: every field");
tsLines.push(" * was emitted from the contract.");
tsLines.push(" *");
tsLines.push(" * `reduceTransparency` implements the mobile half of material-modes.md");
tsLines.push(" * §2.6 Fallback 2 — iOS Reduce Transparency / Android Remove animations are");
tsLines.push(" * reported by AccessibilityInfo, never by a CSS media query, so the swap");
tsLines.push(" * to the paired `-solid` roles has to happen here.");
tsLines.push(" */");
tsLines.push("export function resolveTheme(");
tsLines.push("  paletteId: PaletteId,");
tsLines.push("  materialId: MaterialId,");
tsLines.push("  reduceTransparency = false,");
tsLines.push("): Theme {");
tsLines.push("  const colors = PALETTE_COLORS[paletteId];");
tsLines.push("  const material = PALETTE_MATERIALS[paletteId][materialId];");
tsLines.push("  if (!colors || !material) {");
tsLines.push("    throw new Error(`UNKNOWN_THEME: ${paletteId}/${materialId} is not in tokens.json`);");
tsLines.push("  }");
tsLines.push("  const tier: PaletteTier = PALETTES.find((p) => p.id === paletteId)?.tier ?? \"dark\";");
tsLines.push("  if (!reduceTransparency) {");
tsLines.push("    return { paletteId, materialId, tier, colors, material };");
tsLines.push("  }");
tsLines.push("  return {");
tsLines.push("    paletteId,");
tsLines.push("    materialId,");
tsLines.push("    tier,");
tsLines.push("    colors,");
tsLines.push("    material: {");
tsLines.push("      ...material,");
tsLines.push("      surfaceOverlay: material.surfaceOverlaySolid,");
tsLines.push("      surfaceNav: material.surfaceNavSolid,");
tsLines.push("      surfaceSheet: material.surfaceSheetSolid,");
tsLines.push("      surfacePalette: material.surfacePaletteSolid,");
tsLines.push("      blurPx: 0,");
tsLines.push("      blurIntensity: 0,");
tsLines.push("      translucent: false,");
tsLines.push("      specular: \"none\",");
tsLines.push("      fresnel: \"none\",");
tsLines.push("    },");
tsLines.push("  };");
tsLines.push("}");

// ---------------------------------------------------------------------------
// 8. Write (only now, after every check has passed)
// ---------------------------------------------------------------------------

if (problems.length > 0) {
  process.stderr.write("FATAL: colour values in the contract could not be parsed:\n");
  for (const problem of problems) process.stderr.write(`  - ${problem}\n`);
  process.exit(1);
}

mkdirSync(join(appRoot, "src", "theme"), { recursive: true });
writeFileSync(join(appRoot, "tokens.css"), `${css.join("\n")}\n`, "utf8");
writeFileSync(join(appRoot, "tailwind-theme.generated.js"), `${themeLines.join("\n")}\n`, "utf8");
writeFileSync(join(appRoot, "src", "theme", "tokens.ts"), `${tsLines.join("\n")}\n`, "utf8");

process.stdout.write(
  [
    `contract:   ${contractPath}`,
    `version:    ${contract.version} (${palettes.length} palettes x ${MATERIAL_IDS.length} materials)`,
    `wrote:      ${join(appRoot, "tokens.css")}`,
    `wrote:      ${join(appRoot, "tailwind-theme.generated.js")}`,
    `wrote:      ${join(appRoot, "src", "theme", "tokens.ts")}`,
    "",
  ].join("\n"),
);