// Cache janitor for the monorepo: size, report and wipe regenerable build/tool caches.
// Regenerable by definition — deleting any target only costs recompute time, never data.
import { rm, readdir, stat } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

const ROOT = process.cwd();

const TARGETS = [
  {
    id: "deno-lsp",
    paths: ["apps/gateway/.cache"],
    note: "Deno LSP npm/registry cache (grew past 1.8 GB); refetched from esm.sh on next LSP start",
  },
  {
    id: "next-build",
    paths: ["apps/web/.next", "apps/product-page/.next"],
    note: "Next.js build output; rebuilt by `pnpm build`",
  },
  {
    id: "node-cache",
    paths: ["node_modules/.cache"],
    note: "Tool caches inside node_modules (tsx/esbuild/etc.)",
  },
  {
    id: "coverage",
    paths: ["coverage", "apps/web/coverage", "apps/gateway/coverage"],
    note: "Coverage reports; regenerated by the test scripts",
  },
  {
    id: "playwright",
    paths: ["playwright-report", "test-results", "apps/web/playwright-report", "apps/web/test-results"],
    note: "Playwright report + failure artefacts; regenerated on the next run",
  },
];

function parseArgs(argv) {
  const opts = { apply: false, only: null, intervalMinutes: 0 };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === "--apply") opts.apply = true;
    else if (a === "--only") opts.only = argv[++i]?.split(",").map((s) => s.trim()).filter(Boolean) ?? null;
    else if (a === "--interval") opts.intervalMinutes = Number(argv[++i]);
    else if (a === "--help") opts.help = true;
  }
  return opts;
}

async function dirSize(target) {
  let bytes = 0;
  let files = 0;
  const walk = async (dir) => {
    let entries;
    try {
      entries = await readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) await walk(full);
      else {
        try {
          const s = await stat(full);
          bytes += s.size;
          files += 1;
        } catch {
          /* raced with another process; ignore */
        }
      }
    }
  };
  await walk(target);
  return { bytes, files };
}

function resolveInsideRoot(rel) {
  const abs = path.resolve(ROOT, rel);
  const relFromRoot = path.relative(ROOT, abs);
  if (relFromRoot.startsWith("..") || path.isAbsolute(relFromRoot)) {
    throw new Error(`refusing to touch a path outside the workspace: ${rel}`);
  }
  return abs;
}

function formatMb(bytes) {
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}

async function runOnce(opts) {
  const selected = opts.only
    ? TARGETS.filter((t) => opts.only.includes(t.id))
    : TARGETS;

  if (opts.only) {
    const unknown = opts.only.filter((id) => !TARGETS.some((t) => t.id === id));
    if (unknown.length > 0) {
      console.error(`unknown target(s): ${unknown.join(", ")}`);
      console.error(`known: ${TARGETS.map((t) => t.id).join(", ")}`);
      process.exitCode = 2;
      return 0;
    }
  }

  const vanished = new Set();
  const rows = [];
  let reclaimed = 0;

  for (const target of selected) {
    for (const rel of target.paths) {
      if ([...vanished].some((v) => rel === v || rel.startsWith(`${v}/`))) continue;
      const abs = resolveInsideRoot(rel);
      if (!existsSync(abs)) continue;
      const { bytes, files } = await dirSize(abs);
      if (bytes === 0 && files === 0) continue;
      let status = "would remove";
      if (opts.apply) {
        await rm(abs, { recursive: true, force: true });
        vanished.add(rel);
        reclaimed += bytes;
        status = "removed";
      }
      rows.push({ id: target.id, path: rel, bytes, files, status });
    }
  }

  if (rows.length === 0) {
    console.log("cache-clean: nothing to do, all targets already empty");
  } else {
    console.log(`cache-clean  mode=${opts.apply ? "APPLY" : "DRY-RUN"}`);
    for (const r of rows) {
      console.log(`  ${r.status.padEnd(11)} ${r.id.padEnd(11)} ${formatMb(r.bytes).padStart(10)}  ${String(r.files).padStart(7)} files  ${r.path}`);
    }
    if (opts.apply) {
      console.log(`  total reclaimed: ${formatMb(reclaimed)}`);
    } else {
      const total = rows.reduce((sum, r) => sum + r.bytes, 0);
      console.log(`  total reclaimable: ${formatMb(total)}  (re-run with --apply to free it)`);
    }
  }

  for (const target of selected) {
    if (rows.some((r) => r.id === target.id)) console.log(`  note[${target.id}]: ${target.note}`);
  }

  return reclaimed;
}

const opts = parseArgs(process.argv.slice(2));

if (opts.help) {
  console.log("Usage: node scripts/cache-clean.mjs [--apply] [--only id,id] [--interval minutes]");
  console.log(`Targets: ${TARGETS.map((t) => t.id).join(", ")}`);
  process.exit(0);
}

await runOnce(opts);

if (opts.intervalMinutes > 0) {
  const ms = opts.intervalMinutes * 60_000;
  console.log(`cache-clean: repeating every ${opts.intervalMinutes} minute(s); Ctrl-C to stop`);
  setInterval(() => {
    runOnce(opts).catch((err) => console.error("cache-clean:", err.message));
  }, ms);
}